# Generated by Django 4.2.4 on 2024-01-26 19:37

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
                ('sigla', models.CharField(max_length=255, unique=True)),
                ('rut', models.CharField(max_length=12, null=True)),
                ('direccion', models.CharField(max_length=255, null=True)),
                ('tipo', models.CharField(choices=[('empresa pública', 'Empresa pública'), ('ministerio', 'Minsiterio'), ('municipalidad', 'Municipalidad'), ('servicio público', 'Servicio Público'), ('privado', 'Privado')], default='servicio público', max_length=20)),
            ],
            options={
                'verbose_name': 'Subdirección',
                'verbose_name_plural': 'Instituciones',
                'ordering': ('sigla',),
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('telefono', models.CharField(max_length=255, null=True)),
                ('area', models.CharField(max_length=255, null=True)),
                ('cargo', models.CharField(max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, null=True)),
                ('objetivo', models.TextField(null=True)),
                ('oficio_recibido', models.FileField(upload_to='proyectos/')),
                ('fecha_oficio_recibido', models.DateField(null=True)),
                ('gabinete', models.CharField(max_length=50, null=True)),
                ('timestamp_creacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('estado', models.CharField(choices=[('solicitud recibida', 'Solicitud recibida'), ('confección del protocolo', 'Confección del protocolo'), ('en curso', 'En curso'), ('finalizado', 'Finalizado'), ('rechazado', 'Rechazado')], default='solicitud recibida', max_length=50)),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
            },
        ),
        migrations.CreateModel(
            name='Subdireccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
                ('sigla', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'verbose_name': 'Subdirección',
                'verbose_name_plural': 'Subdirecciones',
                'ordering': ('sigla',),
            },
            managers=[
                ('ojects', django.db.models.manager.Manager()),
            ],
        ),
    ]
