# Generated by Django 4.2.4 on 2024-10-29 12:43

import apps.pc_isla.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipo', models.CharField(choices=[('Bora Bora', 'Bora Bora'), ('Juan Fernández', 'Juan Fernández'), ('Rapa Nui', 'Rapa Nui')], default='Bora Bora', max_length=50)),
                ('horario', models.CharField(choices=[('AM', 'AM'), ('PM', 'PM')], default='AM', max_length=50)),
                ('fecha', models.DateField()),
                ('tipo', models.CharField(choices=[('regular', 'Regular'), ('recuperación', 'Recuperación'), ('extra', 'Extra')], default='regular', max_length=50)),
                ('datetime_ingreso', models.CharField(blank=True, max_length=20, null=True)),
                ('datetime_salida', models.CharField(blank=True, max_length=20, null=True)),
                ('motivo_salida', models.CharField(blank=True, choices=[('fin jornada', 'Fin jornada'), ('proceso ejecutándose', 'Proceso ejecutándose'), ('extracción de datos', 'Extracción de datos'), ('inasistencia anticipada', 'Inasistencia anticipada'), ('asistencia cedida', 'Asistencia cedida'), ('otro', 'Otro')], max_length=50, null=True)),
                ('observacion', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'verbose_name': 'Asistencia',
                'verbose_name_plural': 'Asistencias',
            },
        ),
        migrations.CreateModel(
            name='AsistenciaInvestigador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'AsistenciaInvestigador',
                'verbose_name_plural': 'AsistenciasInvestigador',
            },
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, null=True)),
                ('objetivo', models.TextField(null=True)),
                ('oficio_recibido', models.FileField(max_length=500, upload_to=apps.pc_isla.models.proyecto_upload_path)),
                ('fecha_oficio_recibido', models.DateField(null=True)),
                ('gabinete', models.CharField(max_length=50, null=True)),
                ('timestamp_creacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('estado', models.CharField(choices=[('solicitud recibida', 'Solicitud recibida'), ('confección del protocolo', 'Confección del protocolo'), ('en curso', 'En curso'), ('finalizado', 'Finalizado'), ('rechazado', 'Rechazado')], default='solicitud recibida', max_length=50)),
                ('oficio_respuesta', models.FileField(blank=True, max_length=500, null=True, upload_to=apps.pc_isla.models.respuesta_upload_path)),
                ('fecha_oficio_respuesta', models.DateField(blank=True, null=True)),
                ('protocolo', models.FileField(blank=True, max_length=500, null=True, upload_to=apps.pc_isla.models.protocolo_upload_path)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_termino', models.DateField(blank=True, null=True)),
                ('extendido', models.BooleanField(default=0)),
                ('fecha_extension', models.DateField(blank=True, null=True)),
                ('documento_extension', models.FileField(blank=True, max_length=500, null=True, upload_to=apps.pc_isla.models.documento_extension_upload_path)),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('encargado', 'Encargado'), ('investigador', 'Investigador')], max_length=50)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.persona')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pc_isla.proyecto')),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
            },
        ),
    ]
