# Generated by Django 4.2.4 on 2024-01-29 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pc_isla', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='institucion',
            options={'ordering': ('sigla',), 'verbose_name': 'Institución', 'verbose_name_plural': 'Instituciones'},
        ),
        migrations.AlterField(
            model_name='institucion',
            name='ministerio',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pc_isla.institucion'),
        ),
        migrations.AlterField(
            model_name='institucion',
            name='tipo',
            field=models.CharField(choices=[('empresa pública', 'Empresa pública'), ('ministerio', 'Minsiterio'), ('municipalidad', 'Municipalidad'), ('servicio público', 'Servicio público'), ('privado', 'Privado')], default='servicio público', max_length=20),
        ),
    ]
