# Generated by Django 4.2.4 on 2025-09-29 19:52

import apps.pc_isla.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pc_isla', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Extraccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(blank=True)),
                ('fecha', models.DateField(blank=True)),
                ('estado', models.CharField(blank=True, default='Entregado', max_length=50)),
                ('gabinete', models.CharField(blank=True, max_length=50, null=True)),
                ('informe_revision', models.FileField(blank=True, max_length=500, null=True, upload_to=apps.pc_isla.models.informe_revision_upload_path)),
                ('extraccion_zip', models.FileField(blank=True, max_length=500, null=True, upload_to=apps.pc_isla.models.extraccion_zip_upload_path)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pc_isla.proyecto')),
            ],
            options={
                'verbose_name': 'Extraccion',
                'verbose_name_plural': 'Extracciones',
            },
        ),
    ]
