# Generated by Django 4.2.4 on 2025-09-29 20:09

import apps.pc_isla.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pc_isla', '0003_extraccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='extraccion',
            name='documento_word',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=apps.pc_isla.models.documento_word_upload_path),
        ),
    ]
