# Generated by Django 4.2.4 on 2025-09-29 20:15

from django.db import migrations


def rename_column(apps, schema_editor):
    """
    Rename documento_zip column to extraccion_zip in pc_isla_extraccion table
    """
    with schema_editor.connection.cursor() as cursor:
        # Create a new table with the correct column name
        cursor.execute("""
            CREATE TABLE pc_isla_extraccion_new (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                numero INTEGER,
                fecha date,
                estado varchar(50),
                gabinete varchar(50),
                informe_revision varchar(500),
                extraccion_zip varchar(500),
                proyecto_id bigint,
                documento_word varchar(500),
                FOREIGN KEY (proyecto_id) REFERENCES pc_isla_proyecto (id)
            )
        """)
        
        # Copy data from old table to new table
        cursor.execute("""
            INSERT INTO pc_isla_extraccion_new 
            (id, numero, fecha, estado, gabinete, informe_revision, extraccion_zip, proyecto_id, documento_word)
            SELECT id, numero, fecha, estado, gabinete, informe_revision, documento_zip, proyecto_id, documento_word
            FROM pc_isla_extraccion
        """)
        
        # Drop old table
        cursor.execute("DROP TABLE pc_isla_extraccion")
        
        # Rename new table to original name
        cursor.execute("ALTER TABLE pc_isla_extraccion_new RENAME TO pc_isla_extraccion")


def reverse_rename_column(apps, schema_editor):
    """
    Reverse the rename operation
    """
    with schema_editor.connection.cursor() as cursor:
        # Create a new table with the old column name
        cursor.execute("""
            CREATE TABLE pc_isla_extraccion_new (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                numero INTEGER,
                fecha date,
                estado varchar(50),
                gabinete varchar(50),
                informe_revision varchar(500),
                documento_zip varchar(500),
                proyecto_id bigint,
                documento_word varchar(500),
                FOREIGN KEY (proyecto_id) REFERENCES pc_isla_proyecto (id)
            )
        """)
        
        # Copy data from old table to new table
        cursor.execute("""
            INSERT INTO pc_isla_extraccion_new 
            (id, numero, fecha, estado, gabinete, informe_revision, documento_zip, proyecto_id, documento_word)
            SELECT id, numero, fecha, estado, gabinete, informe_revision, extraccion_zip, proyecto_id, documento_word
            FROM pc_isla_extraccion
        """)
        
        # Drop old table
        cursor.execute("DROP TABLE pc_isla_extraccion")
        
        # Rename new table to original name
        cursor.execute("ALTER TABLE pc_isla_extraccion_new RENAME TO pc_isla_extraccion")


class Migration(migrations.Migration):

    dependencies = [
        ('pc_isla', '0004_extraccion_documento_word'),
    ]

    operations = [
        migrations.RunPython(rename_column, reverse_rename_column),
    ]
