# Generated by Django 4.2.4 on 2024-03-19 20:29

import apps.pc_isla.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pc_isla', '0006_alter_proyecto_oficio_recibido'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='fecha_oficio_respuesta',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='oficio_respuesta',
            field=models.FileField(max_length=500, null=True, upload_to=apps.pc_isla.models.respuesta_upload_path),
        ),
    ]
