# Generated by Django 4.2.4 on 2024-03-19 21:18

import apps.pc_isla.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pc_isla', '0007_proyecto_fecha_oficio_respuesta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='fecha_oficio_respuesta',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='oficio_respuesta',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=apps.pc_isla.models.respuesta_upload_path),
        ),
    ]
