# Generated by Django 4.2.4 on 2024-03-25 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pc_isla', '0008_alter_proyecto_fecha_oficio_respuesta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='email',
            field=models.CharField(max_length=255),
        ),
    ]
