# Generated by Django 4.2.4 on 2024-04-08 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pc_isla', '0010_proyecto_fecha_inicio_proyecto_fecha_termino_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='fecha_inicio',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='fecha_termino',
            field=models.DateField(null=True),
        ),
    ]
