# Generated by Django 4.2.4 on 2024-04-08 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pc_isla', '0011_alter_proyecto_fecha_inicio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='fecha_termino',
            field=models.DateField(blank=True, null=True),
        ),
    ]
