# Generated by Django 4.2.4 on 2024-04-17 19:43

import apps.pc_isla.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pc_isla', '0014_proyecto_fecha_inicio_proyecto_fecha_termino'),
    ]

    operations = [
        migrations.AddField(
            model_name='jornada',
            name='extra',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='protocolo',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=apps.pc_isla.models.protocolo_upload_path),
        ),
    ]
