# Generated by Django 4.2.4 on 2024-04-23 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pc_isla', '0016_jornada_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='jornada',
            name='active',
            field=models.BooleanField(default=1),
        ),
    ]
