# Generated by Django 4.2.4 on 2024-04-23 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pc_isla', '0017_jornada_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('detatime_salida', models.DateTimeField(blank=True, null=True)),
                ('motivo_salida', models.CharField(choices=[('fin jornada', 'Fin jornada'), ('proceso ejecutándose', 'Proceso ejecutándose'), ('otro', 'Otro')], default='fin jornada', max_length=50)),
                ('jornada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pc_isla.jornada')),
            ],
            options={
                'verbose_name': 'Asistencia',
                'verbose_name_plural': 'Asistencias',
            },
        ),
    ]
