# Generated by Django 4.2.4 on 2024-04-23 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pc_isla', '0019_asistencia_detatime_ingreso'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asistencia',
            old_name='detatime_ingreso',
            new_name='datetime_ingreso',
        ),
        migrations.RenameField(
            model_name='asistencia',
            old_name='detatime_salida',
            new_name='datetime_salida',
        ),
    ]
