# Generated by Django 4.2.4 on 2024-05-09 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pc_isla', '0022_alter_asistencia_datetime_ingreso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='extendido',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='institucion',
            name='tipo',
            field=models.CharField(choices=[('empresa pública', 'Empresa pública'), ('ministerio', 'Ministerio'), ('municipalidad', 'Municipalidad'), ('servicio público', 'Servicio público'), ('privado', 'Privado')], default='servicio público', max_length=20),
        ),
    ]
