# Generated by Django 4.2.4 on 2024-05-14 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pc_isla', '0023_proyecto_extendido_alter_institucion_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institucion',
            name='direccion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='institucion',
            name='rut',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.CreateModel(
            name='AsistenciaInvestigador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asistencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pc_isla.asistencia')),
                ('investigador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pc_isla.persona')),
            ],
            options={
                'verbose_name': 'AsistenciaInvestigador',
                'verbose_name_plural': 'AsistenciasInvestigador',
            },
        ),
    ]
