# Generated by Django 4.2.4 on 2024-08-02 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pc_isla', '0025_proyecto_documento_extension_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='apellido',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='rut',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='motivo_salida',
            field=models.CharField(blank=True, choices=[('fin jornada', 'Fin jornada'), ('proceso ejecutándose', 'Proceso ejecutándose'), ('extracción de datos', 'Extracción de datos'), ('otro', 'Otro')], max_length=50, null=True),
        ),
    ]
