# Generated by Django 4.2.4 on 2024-10-23 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
        ('pc_isla', '0026_persona_apellido_persona_rut_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='institucion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.institucion'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='institucion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.institucion'),
        ),
        migrations.DeleteModel(
            name='Institucion',
        ),
    ]
