# Generated by Django 4.2.4 on 2024-10-23 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_subdireccion_persona'),
        ('user', '0013_alter_useraccount_persona'),
        ('pc_isla', '0027_alter_persona_institucion_alter_proyecto_institucion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistenciainvestigador',
            name='investigador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.persona'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='backup_sii',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backup_sii_proyecto', to='base.persona'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='encargado_sii',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='encargado_sii_proyecto', to='base.persona'),
        ),
        migrations.AlterField(
            model_name='rol',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.persona'),
        ),
        migrations.DeleteModel(
            name='Persona',
        ),
        migrations.DeleteModel(
            name='Subdireccion',
        ),
    ]
