# Generated by Django 4.2.4 on 2023-12-14 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccount',
            old_name='is_staff',
            new_name='is_author',
        ),
    ]
