# Generated by Django 4.2.4 on 2023-12-14 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_is_staff_useraccount_is_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='is_author',
        ),
        migrations.AddField(
            model_name='useraccount',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
