# Generated by Django 4.2.4 on 2024-01-30 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pc_isla', '0003_alter_institucion_options_and_more'),
        ('user', '0005_useraccount_is_buscador_admin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='persona',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pc_isla.persona'),
        ),
    ]
