# Generated by Django 4.2.4 on 2024-01-30 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_useraccount_persona'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='persona',
        ),
    ]
