# Generated by Django 4.2.4 on 2024-01-30 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pc_isla', '0004_alter_persona_area_alter_persona_cargo_and_more'),
        ('user', '0009_remove_useraccount_persona'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='persona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pc_isla.persona'),
        ),
    ]
