# Generated by Django 4.2.4 on 2024-01-30 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_useraccount_persona'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='email',
        ),
        migrations.AddField(
            model_name='useraccount',
            name='username',
            field=models.CharField(default='usuario0', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
