# Generated by Django 4.2.4 on 2024-04-23 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_remove_useraccount_email_useraccount_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='is_pc_isla_investigador',
            field=models.BooleanField(default=False),
        ),
    ]
