# Generated by Django 4.2.4 on 2024-10-23 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_subdireccion_persona'),
        ('user', '0012_useraccount_is_pc_isla_investigador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='persona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.persona'),
        ),
    ]
