# Generated by Django 4.2.4 on 2024-10-23 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
                ('sigla', models.CharField(max_length=255, unique=True)),
                ('rut', models.CharField(blank=True, max_length=12, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo', models.CharField(choices=[('empresa pública', 'Empresa pública'), ('ministerio', 'Ministerio'), ('municipalidad', 'Municipalidad'), ('servicio público', 'Servicio público'), ('privado', 'Privado')], default='servicio público', max_length=20)),
                ('ministerio', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.institucion')),
            ],
            options={
                'verbose_name': 'Institución',
                'verbose_name_plural': 'Instituciones',
                'ordering': ('sigla',),
            },
        ),
    ]
