# Generated by Django 4.2.4 on 2023-11-10 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buscador', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nota',
            options={'ordering': ('fecha_creacion',), 'verbose_name': 'Nota', 'verbose_name_plural': 'Notas'},
        ),
        migrations.AlterModelOptions(
            name='query',
            options={'ordering': ('nombre',), 'verbose_name': 'Query', 'verbose_name_plural': 'Queries'},
        ),
        migrations.AddField(
            model_name='nota',
            name='status',
            field=models.CharField(choices=[('publicado', 'Publicado'), ('eliminado', 'Eliminado')], default='publicado', max_length=10),
        ),
        migrations.AddField(
            model_name='query',
            name='status',
            field=models.CharField(choices=[('publicado', 'Publicado'), ('eliminado', 'Eliminado')], default='publicado', max_length=10),
        ),
    ]
