# Generated by Django 4.2.4 on 2023-11-28 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buscador', '0002_alter_nota_options_alter_query_options_nota_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nota',
            options={'ordering': ('-fecha_creacion',), 'verbose_name': 'Nota', 'verbose_name_plural': 'Notas'},
        ),
    ]
